import React from "react";
import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold">Amazonlite</h1>
    </div>
  );
};

Home.displayName = "Home";

export default Home;
